### ISSUE TITLE
cant run on laptop 

### ISSUE THREAD

**Issue by Pcheape** [richarddun/curses_battle_game#1]
error I am getting is "Full screen terminal required to experience the game in SLD (super low definition)"
When I try to run program on my laptop. Even if I am running it in full screen terminal. 

os ubuntu linux 
Python 2.7.6

**Comment by Pcheape** [comment]
latest update is now letting me run but crashes when it tries to draw first enemy .

Traceback (most recent call last):
  File "./logic.py", line 285, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./logic.py", line 113, in main
    Ewin.draw_en_sprite(get_ch_pic(picref[monster]))
  File "/home/cytex/curses_battle_game/arena.py", line 112, in draw_en_sprite
    self.win.addch(yindex,xloc,pxl)
_curses.error: addch() returned ERR

**Comment by richarddun** [comment]
Updated positional logic (from where each character is drawn)
